version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERURL=${SERVER_URL}
      - SERVERPORT=${WIREGUARD_SERVER_PORT}  # Порт WireGuard
      - PEERS=${PEERS}
      - PEERDNS=${WIREGUARD_PEERDNS}
    volumes:
      - ./config/wireguard:/config        # Конфигурация WireGuard
      - /lib/modules:/lib/modules
    ports:
      - "${WIREGUARD_SERVER_PORT}:${WIREGUARD_SERVER_PORT}/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks
    ports:
      - "${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}/tcp"  # Поддержка TCP
      - "${SHADOWSOCKS_PORT}:${SHADOWSOCKS_PORT}/udp"  # Поддержка UDP
    environment:
      - PASSWORD=${SHADOWSOCKS_PASSWORD}
      - METHOD=${SHADOWSOCKS_METHOD}
      - TIMEOUT=${SHADOWSOCKS_TIMEOUT}
    restart: always

  xray:
    image: teddysun/xray
    container_name: xray
    ports:
      - "${XRAY_VLESS_PORT}:${XRAY_VLESS_PORT}/tcp"  # Поддержка VLESS
      - "${XRAY_VLESS_PORT}:${XRAY_VLESS_PORT}/udp"
    volumes:
      - ./config/xray/config.json:/etc/xray/config.json
    environment:
      - UUID=${XRAY_UUID}
      - NETWORK=${XRAY_VLESS_NETWORK}
      - PATH=${XRAY_VLESS_PATH}
    restart: always
