version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - WG_DOMAIN=${WG_DOMAIN}
      - SECRET_KEY_FILE=/run/secrets/secret_key
    volumes:
      - .:/app
    depends_on:
      - db
    secrets:
      - secret_key
    networks:
      - wg_network
    dns:
      - 8.8.8.8

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wg_network

  xray:
    image: teddysun/xray
    ports:
      - "443:443"
    volumes:
      - ./config/xray:/etc/xray
    networks:
      - wg_network

networks:
  wg_network:

volumes:
  postgres_data:

secrets:
  secret_key:
    file: ./secrets/secret_key
