shadowsocks:
  server: ${SHADOWSOCKS_SERVER}
  port: ${SHADOWSOCKS_PORT}
  password: ${SHADOWSOCKS_PASSWORD}
  method: ${SHADOWSOCKS_METHOD}
  timeout: ${SHADOWSOCKS_TIMEOUT}

xray:
  log:
    access: ${XRAY_ACCESS_LOG_PATH}
    error: ${XRAY_ERROR_LOG_PATH}
    loglevel: ${XRAY_LOG_LEVEL}
  inbounds:
    shadowsocks:
      port: ${XRAY_SHADOWSOCKS_PORT}
      method: ${XRAY_SHADOWSOCKS_METHOD}
      password: ${XRAY_SHADOWSOCKS_PASSWORD}
      network: tcp,udp
    wireguard:
      port: ${XRAY_WIREGUARD_PORT}
      secretKey: ${XRAY_WIREGUARD_SECRET_KEY}
      publicKey: ${XRAY_WIREGUARD_PUBLIC_KEY}
      address: "${XRAY_WIREGUARD_ADDRESS}"
      peers: []
      streamSettings:
        network: tcp
    vless:
      port: ${XRAY_VLESS_PORT}
      clients:
        - id: ${XRAY_UUID}
      decryption: none
      streamSettings:
        network: ${XRAY_VLESS_NETWORK}
        wsSettings:
          path: ${XRAY_VLESS_PATH}
  outbounds:
    - protocol: freedom
      settings: {}

wireguard:
  config: |
    [Interface]
    Address = 10.0.0.2/24
    DNS = 1.1.1.1
    PrivateKey = "${WIREGUARD_PRIVATE_KEY}"

    [Peer]
    PublicKey = ${WIREGUARD_SERVER_PUBLIC_KEY}
    Endpoint = ${WIREGUARD_SERVER_IP}:${WIREGUARD_SERVER_PORT}
    AllowedIPs = 0.0.0.0/0
    PersistentKeepalive = 21
